# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01a64dc4358f77f1a284e1c13b7763792008fba6453823020ec078a293c704496501886360a38e7fac4862ad0e961f8ae185559b92bfd78062ed0874c0535bf4

test:
  secret_key_base: 281244837bc4095c6eec789dfd38148f833818e000cc8bb48e3b5d6dda4042f8d6eaea7df7732f7eff2f2b194f1e7c7514271860b638b36c8282c5cc82a2fcf3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
